### PR TITLE
change "login" label to "username" for clarity

### PR DESCRIPTION
**Pull request by dainiuxt**
More explicit than "login" label.

### CODE REVIEW

**Comment by swilgosz** [comment]
@dainiuxt Thanks for your contribution! But why did you just close this PR?

**Comment by dainiuxt** [comment]
I closed it, because it ended with failing some tests, so I thought that
maybe I misunderstand some concept of vue.
Dainius Tulaba
Cell: +370 631 09402 | eitne.lt

**Comment by dainiuxt** [comment]
> @dainiuxt Thanks for your contribution! But why did you just close this PR?

If you think, everything is OK I can reopen it.

**Comment by swilgosz** [comment]
@dainiuxt Yes, it fails, as there is a test checking that label. If you change the label, the test needs to be adjusted ;).

**Comment by dainiuxt** [comment]
> @dainiuxt Yes, it fails, as there is a test checking that label. If you change the label, the test needs to be adjusted ;).

I think from the 3rd time it is OK :) My first PR.

**Comment by swilgosz** [comment]
Congratulations and thanks for your time!

**Comment by dainiuxt** [comment]
> Congratulations and thanks for your time!

My pleasure :) I need to learn git more.

**Pull request merged**
